# Generated by Django 3.2 on 2023-02-26 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0002_userprofile_default_post_code'),
        ('jewelries', '0004_alter_jewelry_inventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('jewelry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to='jewelries.jewelry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to='profiles.userprofile')),
            ],
        ),
    ]
