# Generated by Django 3.2 on 2023-03-05 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jewelries', '0004_alter_jewelry_inventory'),
        ('profiles', '0002_userprofile_default_post_code'),
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlistitem',
            name='jewelry',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='jewelries.jewelry'),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.userprofile'),
        ),
    ]
