# Generated by Django 3.2 on 2023-03-05 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jewelries', '0004_alter_jewelry_inventory'),
        ('wishlist', '0002_auto_20230305_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlistitem',
            name='jewelry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jewelries.jewelry'),
        ),
    ]
