# Generated by Django 3.2 on 2022-10-26 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelries', '0002_auto_20221021_0916'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jewelry',
            options={'verbose_name_plural': 'Jewelries'},
        ),
        migrations.AddField(
            model_name='jewelry',
            name='inventory',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
