# Generated by Django 3.2 on 2022-10-27 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelries', '0003_auto_20221026_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jewelry',
            name='inventory',
            field=models.IntegerField(default=0),
        ),
    ]
