# Generated by Django 3.2 on 2023-03-11 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='email',
            field=models.ManyToManyField(to='newsletter.NewsletterSubscriber'),
        ),
    ]
