# Generated by Django 3.2 on 2022-10-30 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jewelries', '0004_alter_jewelry_inventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=32)),
                ('full_name', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=25)),
                ('address1', models.CharField(max_length=150)),
                ('address2', models.CharField(blank=True, max_length=150)),
                ('city', models.CharField(max_length=80)),
                ('county_province_state', models.CharField(max_length=90)),
                ('country', models.CharField(max_length=90)),
                ('post_code', models.CharField(max_length=20)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('total_paid', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('jewelry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jewelries.jewelry')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderitem', to='checkout.order')),
            ],
        ),
    ]
