# Generated by Django 3.2 on 2023-01-12 22:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20221030_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='lineitem_total',
            field=models.DecimalField(decimal_places=2, default=django.utils.timezone.now, editable=False, max_digits=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderinlineitems', to='checkout.order'),
        ),
    ]
